### ISSUE TITLE
Pattern not actually lispRepr

### ISSUE THREAD

**Issue by PMunch** [krux02/ast-pattern-matching#7]
In the documentation it says:

>  The of-branch is a tree that can at any time be generated via `lispRepr` on an arbitrary `NimNode`.

This isn't entirely true, when you call lispRepr you get the result with the `nnk` prefix.

**Comment by krux02** [comment]
Well, that used to be true. I think i have to update the documentation. Maybe I have to implement my own matchRepr then. But it is still very close to the lisp repr. Thank you for the feedback though. I don't have automatic tests for documentation correctness.
